name: Create Issues from TODO Comments

on:
  push:
    branches:
      - main
      - develop

permissions:
  issues: write
  contents: read

jobs:
  todo-to-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run TODO to Issue
        uses: alstr/todo-to-issue-action@v5
        id: todo
        with:
          CLOSE_ISSUES: true
          AUTO_P: true
          AUTO_ASSIGN: true
          IDENTIFIERS: |
            [
              {"name": "TODO", "labels": ["todo"]},
              {"name": "FIXME", "labels": ["bug", "fixme"]},
              {"name": "HACK", "labels": ["hack"]},
              {"name": "BUG", "labels": ["bug"]},
              {"name": "XXX", "labels": ["xxx"]}
            ]